var d = new Date()
console.log(d)
console.log(d.getFullYear())
console.log(d.getMonth())
console.log(d.getDate())
console.log(d.getUTCDate())
console.log(d.getTime())
console.log(d.toLocaleDateString())
console.log(d.toLocaleTimeString())